const colors = {
  light: {
    text: '#0F172A',
    tint: '#1A56DB',
    background: '#F8FAFF',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#1A56DB',
    primaryForeground: '#FFFFFF',
    primaryLight: '#EEF2FF',
    secondary: '#F1F5F9',
    secondaryForeground: '#1E293B',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#F97316',
    accentForeground: '#FFFFFF',
    accentLight: '#FFF7ED',
    success: '#16A34A',
    successLight: '#F0FDF4',
    successForeground: '#FFFFFF',
    warning: '#D97706',
    warningLight: '#FFFBEB',
    warningForeground: '#FFFFFF',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
    // Role colors
    morador: '#1A56DB',
    moradorLight: '#EEF2FF',
    lider: '#7C3AED',
    liderLight: '#F5F3FF',
    empresa: '#0D9488',
    empresaLight: '#F0FDFA',
    prefeitura: '#B45309',
    prefeituraLight: '#FFFBEB',
  },
  dark: {
    text: '#F8FAFC',
    tint: '#60A5FA',
    background: '#0A1628',
    foreground: '#F8FAFC',
    card: '#131F35',
    cardForeground: '#F8FAFC',
    primary: '#3B82F6',
    primaryForeground: '#FFFFFF',
    primaryLight: '#1E3A5F',
    secondary: '#1E2D4A',
    secondaryForeground: '#CBD5E1',
    muted: '#1E2D4A',
    mutedForeground: '#94A3B8',
    accent: '#FB923C',
    accentForeground: '#FFFFFF',
    accentLight: '#431407',
    success: '#22C55E',
    successLight: '#052E16',
    successForeground: '#FFFFFF',
    warning: '#FCD34D',
    warningLight: '#451A03',
    warningForeground: '#1C1917',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#1E3A5F',
    input: '#1E3A5F',
    morador: '#3B82F6',
    moradorLight: '#1E3A5F',
    lider: '#A78BFA',
    liderLight: '#2E1065',
    empresa: '#2DD4BF',
    empresaLight: '#042F2E',
    prefeitura: '#FCD34D',
    prefeituraLight: '#451A03',
  },
  radius: 14,
};

export default colors;
